from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.groupBoxOptions = QtWidgets.QGroupBox(MainWindow)
        self.groupBoxOptions.setGeometry(QtCore.QRect(40, 30, 271, 421))
        self.groupBoxOptions.setObjectName("groupBoxOptions")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBoxOptions)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 251, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_options = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_options.setContentsMargins(5, 11, 11, 11)
        self.verticalLayout_options.setSpacing(10)
        self.verticalLayout_options.setObjectName("verticalLayout_options")
        self.label_step_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_step_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_step_1.setObjectName("label_step_1")
        self.verticalLayout_options.addWidget(self.label_step_1)
        self.horizontalLayout_step = QtWidgets.QHBoxLayout()
        self.horizontalLayout_step.setSpacing(6)
        self.horizontalLayout_step.setObjectName("horizontalLayout_step")
        self.label_step_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_step_2.setObjectName("label_step_2")
        self.horizontalLayout_step.addWidget(self.label_step_2)
        self.lineEdit_step = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_step.setObjectName("lineEdit_step")
        self.horizontalLayout_step.addWidget(self.lineEdit_step)
        self.verticalLayout_options.addLayout(self.horizontalLayout_step)
        self.label_n_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_n_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_n_1.setObjectName("label_n_1")
        self.verticalLayout_options.addWidget(self.label_n_1)
        self.horizontalLayout_n = QtWidgets.QHBoxLayout()
        self.horizontalLayout_n.setSpacing(6)
        self.horizontalLayout_n.setObjectName("horizontalLayout_n")
        self.label_n_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_n_2.setObjectName("label_n_2")
        self.horizontalLayout_n.addWidget(self.label_n_2)
        self.lineEdit_n = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.horizontalLayout_n.addWidget(self.lineEdit_n)
        self.verticalLayout_options.addLayout(self.horizontalLayout_n)
        self.label_width_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_width_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_width_1.setObjectName("label_width_1")
        self.verticalLayout_options.addWidget(self.label_width_1)
        self.horizontalLayout_width = QtWidgets.QHBoxLayout()
        self.horizontalLayout_width.setSpacing(6)
        self.horizontalLayout_width.setObjectName("horizontalLayout_width")
        self.label_width_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_width_2.setObjectName("label_width_2")
        self.horizontalLayout_width.addWidget(self.label_width_2)
        self.lineEdit_width = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.horizontalLayout_width.addWidget(self.lineEdit_width)
        self.verticalLayout_options.addLayout(self.horizontalLayout_width)
        self.checkBox_iterative = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_iterative.setObjectName("checkBox_iterative")
        self.verticalLayout_options.addWidget(self.checkBox_iterative)
        self.checkBox_filter = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_filter.setObjectName("checkBox_filter")
        self.verticalLayout_options.addWidget(self.checkBox_filter)
        self.pushButton_apply = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_apply.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_apply.setMaximumSize(QtCore.QSize(241, 41))
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.verticalLayout_options.addWidget(self.pushButton_apply)
        self.groupSave = QtWidgets.QGroupBox(MainWindow)
        self.groupSave.setGeometry(QtCore.QRect(40, 500, 271, 461))
        self.groupSave.setObjectName("groupSave")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupSave)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 251, 421))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_save = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_save.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_save.setSpacing(10)
        self.verticalLayout_save.setObjectName("verticalLayout_save")
        self.horizontalLayout_name = QtWidgets.QHBoxLayout()
        self.horizontalLayout_name.setSpacing(6)
        self.horizontalLayout_name.setObjectName("horizontalLayout_name")
        self.label_name = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_name.addWidget(self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_name.addWidget(self.lineEdit_name)
        self.verticalLayout_save.addLayout(self.horizontalLayout_name)
        self.horizontalLayout_surname = QtWidgets.QHBoxLayout()
        self.horizontalLayout_surname.setSpacing(6)
        self.horizontalLayout_surname.setObjectName("horizontalLayout_surname")
        self.label_surname = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_surname.setObjectName("label_surname")
        self.horizontalLayout_surname.addWidget(self.label_surname)
        self.lineEdit_surname = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.horizontalLayout_surname.addWidget(self.lineEdit_surname)
        self.verticalLayout_save.addLayout(self.horizontalLayout_surname)
        self.horizontalLayout_id = QtWidgets.QHBoxLayout()
        self.horizontalLayout_id.setSpacing(6)
        self.horizontalLayout_id.setObjectName("horizontalLayout_id")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_id.addWidget(self.label_2)
        self.lineEdit_id = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.horizontalLayout_id.addWidget(self.lineEdit_id)
        self.verticalLayout_save.addLayout(self.horizontalLayout_id)
        self.horizontalLayout_date = QtWidgets.QHBoxLayout()
        self.horizontalLayout_date.setSpacing(6)
        self.horizontalLayout_date.setObjectName("horizontalLayout_date")
        self.label_date = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_date.setObjectName("label_date")
        self.horizontalLayout_date.addWidget(self.label_date)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget_5)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2019, 3, 29))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_date.addWidget(self.dateEdit)
        self.verticalLayout_save.addLayout(self.horizontalLayout_date)
        self.horizontalLayout_comment = QtWidgets.QHBoxLayout()
        self.horizontalLayout_comment.setSpacing(6)
        self.horizontalLayout_comment.setObjectName("horizontalLayout_comment")
        self.label_comment = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_comment.setObjectName("label_comment")
        self.horizontalLayout_comment.addWidget(self.label_comment)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_5)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_comment.addWidget(self.plainTextEdit)
        self.verticalLayout_save.addLayout(self.horizontalLayout_comment)
        self.pushButton_save = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_save.setMinimumSize(QtCore.QSize(241, 41))
        self.pushButton_save.setMaximumSize(QtCore.QSize(250, 41))
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout_save.addWidget(self.pushButton_save)
        self.groupBoxSimulation = QtWidgets.QGroupBox(MainWindow)
        self.groupBoxSimulation.setGeometry(QtCore.QRect(360, 30, 1501, 921))
        self.groupBoxSimulation.setObjectName("groupBoxSimulation")
        self.pushButton_browse = QtWidgets.QPushButton(self.groupBoxSimulation)
        self.pushButton_browse.setGeometry(QtCore.QRect(100, 580, 281, 61))
        self.pushButton_browse.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.label_img_out = QtWidgets.QLabel(self.groupBoxSimulation)
        self.label_img_out.setGeometry(QtCore.QRect(990, 90, 400, 400))
        self.label_img_out.setMinimumSize(QtCore.QSize(400, 400))
        self.label_img_out.setMaximumSize(QtCore.QSize(400, 400))
        self.label_img_out.setAutoFillBackground(True)
        self.label_img_out.setText("")
        self.label_img_out.setObjectName("label_img_out")
        self.label_img_sin = QtWidgets.QLabel(self.groupBoxSimulation)
        self.label_img_sin.setGeometry(QtCore.QRect(510, 90, 400, 400))
        self.label_img_sin.setMinimumSize(QtCore.QSize(400, 400))
        self.label_img_sin.setMaximumSize(QtCore.QSize(400, 400))
        self.label_img_sin.setAutoFillBackground(True)
        self.label_img_sin.setText("")
        self.label_img_sin.setObjectName("label_img_sin")
        self.label_img_in = QtWidgets.QLabel(self.groupBoxSimulation)
        self.label_img_in.setGeometry(QtCore.QRect(30, 90, 400, 400))
        self.label_img_in.setMinimumSize(QtCore.QSize(400, 400))
        self.label_img_in.setMaximumSize(QtCore.QSize(400, 400))
        self.label_img_in.setAutoFillBackground(True)
        self.label_img_in.setText("")
        self.label_img_in.setObjectName("label_img_in")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBoxSimulation)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 1431, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_tag_in = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_tag_in.setMinimumSize(QtCore.QSize(0, 35))
        self.label_tag_in.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tag_in.setFont(font)
        self.label_tag_in.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_tag_in.setObjectName("label_tag_in")
        self.horizontalLayout.addWidget(self.label_tag_in)
        self.label_tag_sin = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_tag_sin.setMinimumSize(QtCore.QSize(0, 35))
        self.label_tag_sin.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tag_sin.setFont(font)
        self.label_tag_sin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_tag_sin.setObjectName("label_tag_sin")
        self.horizontalLayout.addWidget(self.label_tag_sin)
        self.label_tag_out = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_tag_out.setMinimumSize(QtCore.QSize(0, 35))
        self.label_tag_out.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_tag_out.setFont(font)
        self.label_tag_out.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_tag_out.setObjectName("label_tag_out")
        self.horizontalLayout.addWidget(self.label_tag_out)
        self.label_statistic = QtWidgets.QLabel(self.groupBoxSimulation)
        self.label_statistic.setGeometry(QtCore.QRect(480, 580, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_statistic.setFont(font)
        self.label_statistic.setObjectName("label_statistic")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Symulator tomografu komputerowego"))
        self.groupBoxOptions.setTitle(_translate("MainWindow", "Opcje"))
        self.label_step_1.setText(_translate("MainWindow", "Krok układu emiter/detektr [°]"))
        self.label_step_2.setText(_translate("MainWindow", "Δα = "))
        self.label_n_1.setText(_translate("MainWindow", "Liczba detektorów"))
        self.label_n_2.setText(_translate("MainWindow", "n ="))
        self.label_width_1.setText(_translate("MainWindow", "Rozpiętość układu emiter/detektor [°]"))
        self.label_width_2.setText(_translate("MainWindow", "l ="))
        self.checkBox_iterative.setText(_translate("MainWindow", "ładowanie iteracyjne"))
        self.checkBox_filter.setText(_translate("MainWindow", "filtrowanie"))
        self.pushButton_apply.setText(_translate("MainWindow", "Zatwierdź"))
        self.groupSave.setTitle(_translate("MainWindow", "Zapis badania"))
        self.label_name.setText(_translate("MainWindow", "Imię"))
        self.label_surname.setText(_translate("MainWindow", "Nazwisko"))
        self.label_2.setText(_translate("MainWindow", "PESEL"))
        self.label_date.setText(_translate("MainWindow", "Data badania"))
        self.label_comment.setText(_translate("MainWindow", "Komentarz"))
        self.pushButton_save.setText(_translate("MainWindow", "Zapisz"))
        self.groupBoxSimulation.setTitle(_translate("MainWindow", "Symulacja"))
        self.pushButton_browse.setText(_translate("MainWindow", "Wybierz plik..."))
        self.label_tag_in.setText(_translate("MainWindow", "Obraz wejściowy"))
        self.label_tag_sin.setText(_translate("MainWindow", "Sinogram"))
        self.label_tag_out.setText(_translate("MainWindow", "Obraz wyjściowy"))
